# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: artifact

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gobra
        uses: actions/checkout@v2
        with:
          path: gobra

      # build docker image
      - name: Docker build
        run: docker build -t gobraverifier/gobra-artifact:v1 .
        working-directory: gobra/artifact

      # save docker image
      - name: Docker save
        run: docker save -o gobra_docker_image.tar gobraverifier/gobra-artifact:v1
        working-directory: gobra/artifact

      - name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: gobra_docker_image.tar
          path: gobra/artifact/gobra_docker_image.tar

  test-image:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v2
        with:
          name: gobra_docker_image.tar

      - name: Load docker image
        run: docker load -i gobra_docker_image.tar

      - name: Run single file
        run: docker run gobraverifier/gobra-artifact:v1 /bin/bash gobra.sh /test_suite/regressions/examples/example-2-1.gobra

      - name: Run regressions
        run: docker run gobraverifier/gobra-artifact:v1 /bin/bash regressions.sh
