# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: artifact

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gobra
        uses: actions/checkout@v2
        with:
          path: gobra

      # build docker container
      - name: Docker build
        run: docker build -t local .
        working-directory: gobra/artifact

      - name: Run regressions
        run: docker run local /bin/bash regressions.sh
