# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: test

on:
  push: # run this workflow on every push
  pull_request: # run this workflow on every pull_request

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    container: gobraverifier/gobra-base:v2
    steps:
      - name: Checkout Gobra
        uses: actions/checkout@v2
        with:
          path: gobra

      # clone Viper dependencies
      - name: Checkout Silver
        uses: actions/checkout@v2
        with:
          repository: viperproject/silver
          path: silver
      - name: Checkout Silicon
        uses: actions/checkout@v2
        with:
          repository: viperproject/silicon
          path: silicon
      - name: Checkout Carbon
        uses: actions/checkout@v2
        with:
          repository: viperproject/carbon
          path: carbon
      - name: Checkout ViperServer
        uses: actions/checkout@v2
        with:
          repository: viperproject/viperserver
          path: viperserver

      - name: Java Version
        run: java --version
      - name: Z3 Version
        run: z3 -version
      - name: Silver Commit
        run: echo "Silver commit:" $(git -C silver rev-parse HEAD)
      - name: Silicon Commit
        run: echo "Silicon commit:" $(git -C silicon rev-parse HEAD)
      - name: Carbon Commit
        run: echo "Carbon commit:" $(git -C carbon rev-parse HEAD)
      - name: ViperServer Commit
        run: echo "ViperServer commit:" $(git -C viperserver rev-parse HEAD)

      # create symlinks between and to Viper dependencies:
      - name: Create Silicon's sym links
        run: ln --symbolic ../silver
        working-directory: silicon
      - name: Create Carbon's sym links
        run: ln --symbolic ../silver
        working-directory: carbon
      - name: Create ViperServers's sym links
        run: ln --symbolic ../silver; ln --symbolic ../silicon; ln --symbolic ../carbon
        working-directory: viperserver
      - name: Create Gobra's sym links
        run: ln --symbolic ../silver; ln --symbolic ../silicon; ln --symbolic ../carbon; ln --symbolic ../viperserver
        working-directory: gobra

      - name: Set sbt cache variables
        run: echo "SBT_OPTS=-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy" >> $GITHUB_ENV
        # note that the cache path is relative to the directory in which sbt is invoked.

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            gobra/sbt-cache/.sbtboot
            gobra/sbt-cache/.boot
            gobra/sbt-cache/.ivy/cache
            gobra/project/target
            gobra/target
            viperserver/project/target
            viperserver/target
            carbon/project/target
            carbon/target
            silicon/project/target
            silicon/target
            silver/project/target
            silver/target
          # use run ID as primary key to avoid a cache hit on the primary key (but on a restore key).
          # this ensures that an updated version of above's directories will be added to the cache and used next time.
          # if instead the key is based on hashing some sbt build files, there will be a cache hit on the primary key
          # (unless the build files have changed) and the updated directories won't be added to the cache (because
          # `actions/cache` skips the cache update after a primary key hit). Hence, the next build job will need to
          # recompile more source files than necessary as compilation will use on an outdated cache.
          # note that `actions/cache` uses a sophisticated logic based on the current branch and the cache versions' age
          # to select a particular cache version if multiple versions match the restore keys.
          key: ${{ runner.os }}-sbt-${{ github.run_id }}
          # restore-keys: |
          #   ${{ runner.os }}-sbt-

      - name: Execute all tests
        run: sbt test
        working-directory: gobra
